# Setup
setup: supervised

# Dataset
train_db_name: google_commands
val_db_name: google_commands
db_name: google_commands
num_labels: 35

# Model
backbone: Resnet18
model_kwargs:
   head: mlp
   num_labels: 35

# Loss
criterion: supervised
criterion_kwargs:
   temperature: None 

# Hyperparameters
epochs: 250
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001 
   momentum: 0.9
   lr: 0.1
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1
batch_size: 256
num_workers: 12

# Transformations
augmentation_strategy: audio 
augmentation_kwargs:
   random_resized_crop:
      size: 32
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

spectogram_kwargs:
   sample_rate: 16000
   n_fft: 512
   n_mels: 40
   win_size: 0.02
   win_stride: 0.01
